[build]
  publish = "client/dist"
  command = "node build-netlify.js"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=86400, s-maxage=86400"

[[headers]]
  for = "/rss.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"
    Content-Type = "application/rss+xml; charset=utf-8"